import { Inter } from 'next/font/google';

import 'antd/dist/reset.css';
import './globals.css';
import Providers from '@/components/Providers';
import { ReactNode } from 'react';
import Layout from '@/components/Layout';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<Layout>{children}</Layout>
				</Providers>
			</body>
		</html>
	);
}
